version: '3'

services:
    amplify:
        build: ./
        ports:
            - "3000:3000"
            - "3001:3001"
        volumes:
            - ./:/var/www/amplify-demo/
            - ./aws/:/root/.aws/
        tty: true